version: "3"
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  products:
    build: ./src/products
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_started
  catalogs:
    build: ./src/catalogs
    ports:
      - "4000:4000"